#!/usr/bin/env bash
# 0. World wide web

print_domain() {
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2' | awk -F " " '{split($1, arr, ".")};{print "The subdomain " arr[1] " is a " $4 " record and points to " $5}'
}

if [ $# -eq 2 ]
then
	print_domain "$1" "$2"
elif [ $# -eq 1 ]
then
	for arr in "www" "lb-01" "web-01" "web-02"
	do
		print_domain "$1" "$arr"
	done
fi
